### ISSUE TITLE
Textile Instance restructuring

### ISSUE THREAD

**Issue by Rashmi-278** [g2entgroup/creative-ui-2.2#79]
Textile Instance is not being persisted, as a result user needs to signin on every action for ex ; upload , view my bucket etc.

What is needed is , 

1) a smooth integration of Walletconect useing usedapp/core lib 
2) textile integration with the lib
3) create buckets for each user , same password same bucket instance 
4) patch the current CRUD of textile

**Comment by gawainb** [comment]
We actually have a recent fix for this. 

However, I think we need a way to display whether someone is actually fully signed in under Textile.
